### ISSUE TITLE
Error when running application

### ISSUE THREAD

**Issue by naheedmk** [ingenuiq/es-cqrs-akka-cluster-full-example#2]
Getting following error when starting the application

Exception in thread "main" java.lang.ClassCastException: class scala.runtime.Nothing$ is not assignable from class akka.discovery.SimpleServiceDiscovery
	at akka.actor.ReflectiveDynamicAccess.$anonfun$getClassFor$1(ReflectiveDynamicAccess.scala:24)
	at scala.util.Try$.apply(Try.scala:213)
	at akka.actor.ReflectiveDynamicAccess.getClassFor(ReflectiveDynamicAccess.scala:21)
	at akka.discovery.Discovery$.checkClassPathForOldDiscovery(Discovery.scala:111)
	at akka.discovery.Discovery.<init>(Discovery.scala:17)
	at akka.discovery.Discovery$.createExtension(Discovery.scala:103)
	at akka.discovery.Discovery$.createExtension(Discovery.scala:96)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:962)

**Comment by Reeebuuk** [comment]
Thx for reporting, will take a look and fix :)

**Comment by Reeebuuk** [comment]
I've run `/docker/docker-compose -f docker-compose-essentials.yml` + `sbt run` 
Hit it with create note and fetch note, no issues. Can you tell me where do you see the error @naheedmk ?

**Comment by naheedmk** [comment]
when executing sbt run, getting following exception. akka http not starting on port 9001


] 12:12:34,150 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set

[info] 12:12:34,150 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]

[info] 12:12:34,157 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]

[info] 12:12:34,158 |-ERROR in ch.qos.logback.core.joran.conditional.IfAction - Could not find Janino library on the class path. Skipping conditional processing.

[info] 12:12:34,158 |-ERROR in ch.qos.logback.core.joran.conditional.IfAction - See also http://logback.qos.ch/codes.html#ifJanino

[info] 12:12:34,159 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - Encoder has not been set. Cannot invoke its init method.

[info] 12:12:34,159 |-ERROR in ch.qos.logback.core.ConsoleAppender[STDOUT] - No encoder set for the appender named "STDOUT".

[info] 12:12:34,159 |-WARN in ch.qos.logback.core.joran.action.AppenderAction - The object at the of the stack is not the appender named [STDOUT] pushed earlier.

[info] 12:12:34,159 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.FileAppender]

[info] 12:12:34,161 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]

[info] 12:12:34,169 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property

[info] 12:12:34,191 |-INFO in ch.qos.logback.core.FileAppender[FILE] - File property is set to [target/note.log]

[info] 12:12:34,194 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG

[info] 12:12:34,194 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]

[info] 12:12:34,223 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]

[info] 12:12:34,223 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.datastax.driver.core] to INFO

[info] 12:12:34,223 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [akka] to DEBUG

[info] 12:12:34,223 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.zaxxer] to WARN

[info] 12:12:34,223 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [io.netty] to WARN

[info] 12:12:34,223 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [slick] to INFO

[info] 12:12:34,223 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.

[info] 12:12:34,224 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@342a5b57 - Registering current configuration as safe fallback point

[error] Exception in thread "main" java.lang.ClassCastException: class scala.runtime.Nothing$ is not assignable from class akka.discovery.SimpleServiceDiscovery

[error]  at akka.actor.ReflectiveDynamicAccess.$anonfun$getClassFor$1(ReflectiveDynamicAccess.scala:24)

[error]  at scala.util.Try$.apply(Try.scala:213)

[error]  at akka.actor.ReflectiveDynamicAccess.getClassFor(ReflectiveDynamicAccess.scala:21)

[error]  at akka.discovery.Discovery$.checkClassPathForOldDiscovery(Discovery.scala:111)

[error]  at akka.discovery.Discovery.<init>(Discovery.scala:17)

[error]  at akka.discovery.Discovery$.createExtension(Discovery.scala:103)

[error]  at akka.discovery.Discovery$.createExtension(Discovery.scala:96)

[error]  at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:962)

[error]  at akka.actor.ExtensionId.apply(Extension.scala:79)

[error]  at akka.actor.ExtensionId.apply$(Extension.scala:78)

[error]  at akka.discovery.Discovery$.apply(Discovery.scala:97)

[error]  at akka.management.cluster.bootstrap.ClusterBootstrap.<init>(ClusterBootstrap.scala:46)

[error]  at akka.management.cluster.bootstrap.ClusterBootstrap$.createExtension(ClusterBootstrap.scala:114)

[error]  at akka.management.cluster.bootstrap.ClusterBootstrap$.createExtension(ClusterBootstrap.scala:108)

[error]  at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:962)

[error]  at akka.management.scaladsl.AkkaManagement.$anonfun$loadRouteProviders$1(AkkaManagement.scala:258)

[error]  at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)

[error]  at scala.collection.immutable.List.foreach(List.scala:392)

[error]  at scala.collection.TraversableLike.map(TraversableLike.scala:237)

[error]  at scala.collection.TraversableLike.map$(TraversableLike.scala:230)

[error]  at scala.collection.immutable.List.map(List.scala:298)

[error]  at akka.management.scaladsl.AkkaManagement.loadRouteProviders(AkkaManagement.scala:235)

[error]  at akka.management.scaladsl.AkkaManagement.<init>(AkkaManagement.scala:75)

[error]  at akka.management.scaladsl.AkkaManagement$.createExtension(AkkaManagement.scala:51)

[error]  at akka.management.scaladsl.AkkaManagement$.createExtension(AkkaManagement.scala:45)

[error]  at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:962)

[error]  at akka.actor.ExtensionId.apply(Extension.scala:79)

[error]  at akka.actor.ExtensionId.apply$(Extension.scala:78)

[error]  at akka.management.scaladsl.AkkaManagement$.apply(AkkaManagement.scala:45)

[error]  at com.ingenuiq.note.Main$.delayedEndpoint$com$ingenuiq$note$Main$1(Main.scala:46)

[error]  at com.ingenuiq.note.Main$delayedInit$body.apply(Main.scala:22)

[error]  at scala.Function0.apply$mcV$sp(Function0.scala:39)

[error]  at scala.Function0.apply$mcV$sp$(Function0.scala:39)

[error]  at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)

[error]  at scala.App.$anonfun$main$1$adapted(App.scala:80)



 

    On Saturday, June 29, 2019, 08:24:54 AM CDT, Krunoslav Uzelac <notifications@github.com> wrote:  
 
 
I've run /docker/docker-compose -f docker-compose-essentials.yml + sbt run
Hit it with create note and fetch note, no issues. Can you tell me where do you see the error @naheedmk ?

**Comment by naheedmk** [comment]
I am trying to run this on local machine (no K8s), it seems failure is discovery, specifically on :

| io.dns.resolver = "async-dns" |
|  |  |
|  |  discovery { |
|  |  method = "akka-dns" |
|  |  kubernetes-api { |
|  |  pod-namespace = "default" |
|  |  pod-label-selector = "app=akka-simple-cluster" |
|  |  pod-port-name = "akka-cluster-note" |
|  |  } |
|  |  } |




    On Sunday, June 30, 2019, 12:20:56 PM CDT, Kunnummal Naheed Madathummal <naheedmk@yahoo.com> wrote:  
 
 when executing sbt run, getting following exception. akka http not starting on port 9001


] 12:12:34,150 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set

[info] 12:12:34,150 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]

[info] 12:12:34,157 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]

[info] 12:12:34,158 |-ERROR in ch.qos.logback.core.joran.conditional.IfAction - Could not find Janino library on the class path. Skipping conditional processing.

[info] 12:12:34,158 |-ERROR in ch.qos.logback.core.joran.conditional.IfAction - See also http://logback.qos.ch/codes.html#ifJanino

[info] 12:12:34,159 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - Encoder has not been set. Cannot invoke its init method.

[info] 12:12:34,159 |-ERROR in ch.qos.logback.core.ConsoleAppender[STDOUT] - No encoder set for the appender named "STDOUT".

[info] 12:12:34,159 |-WARN in ch.qos.logback.core.joran.action.AppenderAction - The object at the of the stack is not the appender named [STDOUT] pushed earlier.

[info] 12:12:34,159 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.FileAppender]

[info] 12:12:34,161 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]

[info] 12:12:34,169 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property

[info] 12:12:34,191 |-INFO in ch.qos.logback.core.FileAppender[FILE] - File property is set to [target/note.log]

[info] 12:12:34,194 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG

[info] 12:12:34,194 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]

[info] 12:12:34,223 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]

[info] 12:12:34,223 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.datastax.driver.core] to INFO

[info] 12:12:34,223 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [akka] to DEBUG

[info] 12:12:34,223 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.zaxxer] to WARN

[info] 12:12:34,223 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [io.netty] to WARN

[info] 12:12:34,223 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [slick] to INFO

[info] 12:12:34,223 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.

[info] 12:12:34,224 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@342a5b57 - Registering current configuration as safe fallback point

[error] Exception in thread "main" java.lang.ClassCastException: class scala.runtime.Nothing$ is not assignable from class akka.discovery.SimpleServiceDiscovery

[error]  at akka.actor.ReflectiveDynamicAccess.$anonfun$getClassFor$1(ReflectiveDynamicAccess.scala:24)

[error]  at scala.util.Try$.apply(Try.scala:213)

[error]  at akka.actor.ReflectiveDynamicAccess.getClassFor(ReflectiveDynamicAccess.scala:21)

[error]  at akka.discovery.Discovery$.checkClassPathForOldDiscovery(Discovery.scala:111)

[error]  at akka.discovery.Discovery.<init>(Discovery.scala:17)

[error]  at akka.discovery.Discovery$.createExtension(Discovery.scala:103)

[error]  at akka.discovery.Discovery$.createExtension(Discovery.scala:96)

[error]  at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:962)

[error]  at akka.actor.ExtensionId.apply(Extension.scala:79)

[error]  at akka.actor.ExtensionId.apply$(Extension.scala:78)

[error]  at akka.discovery.Discovery$.apply(Discovery.scala:97)

[error]  at akka.management.cluster.bootstrap.ClusterBootstrap.<init>(ClusterBootstrap.scala:46)

[error]  at akka.management.cluster.bootstrap.ClusterBootstrap$.createExtension(ClusterBootstrap.scala:114)

[error]  at akka.management.cluster.bootstrap.ClusterBootstrap$.createExtension(ClusterBootstrap.scala:108)

[error]  at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:962)

[error]  at akka.management.scaladsl.AkkaManagement.$anonfun$loadRouteProviders$1(AkkaManagement.scala:258)

[error]  at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)

[error]  at scala.collection.immutable.List.foreach(List.scala:392)

[error]  at scala.collection.TraversableLike.map(TraversableLike.scala:237)

[error]  at scala.collection.TraversableLike.map$(TraversableLike.scala:230)

[error]  at scala.collection.immutable.List.map(List.scala:298)

[error]  at akka.management.scaladsl.AkkaManagement.loadRouteProviders(AkkaManagement.scala:235)

[error]  at akka.management.scaladsl.AkkaManagement.<init>(AkkaManagement.scala:75)

[error]  at akka.management.scaladsl.AkkaManagement$.createExtension(AkkaManagement.scala:51)

[error]  at akka.management.scaladsl.AkkaManagement$.createExtension(AkkaManagement.scala:45)

[error]  at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:962)

[error]  at akka.actor.ExtensionId.apply(Extension.scala:79)

[error]  at akka.actor.ExtensionId.apply$(Extension.scala:78)

[error]  at akka.management.scaladsl.AkkaManagement$.apply(AkkaManagement.scala:45)

[error]  at com.ingenuiq.note.Main$.delayedEndpoint$com$ingenuiq$note$Main$1(Main.scala:46)

[error]  at com.ingenuiq.note.Main$delayedInit$body.apply(Main.scala:22)

[error]  at scala.Function0.apply$mcV$sp(Function0.scala:39)

[error]  at scala.Function0.apply$mcV$sp$(Function0.scala:39)

[error]  at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)

[error]  at scala.App.$anonfun$main$1$adapted(App.scala:80)



 

    On Saturday, June 29, 2019, 08:24:54 AM CDT, Krunoslav Uzelac <notifications@github.com> wrote:  
 
 
I've run /docker/docker-compose -f docker-compose-essentials.yml + sbt run
Hit it with create note and fetch note, no issues. Can you tell me where do you see the error @naheedmk ?

**Comment by Reeebuuk** [comment]
I managed to get it running now, can tour try again @naheedmk ? :)

**Comment by Reeebuuk** [comment]
Fixed, try it now.

Will add docs and make akka-management port configurable
